let shopItemsData = [
    {
      id: "jfhgbvnscs",
      name: "Party Blazzer",
      price: 3000,
      desc: "Stunning Blazzer for Parties and Functionss.",
      img: "images/img-1.jpeg",
    },
    {
      id: "ioytrhndcv",
      name: "Casual Shirt",
      price: 800,
      desc: "Beautiful Casual Shirts.",
      img: "images/img-2.jpeg",
    },
    {
      id: "wuefbncxbsn",
      name: "Jeans",
      price: 1200,
      desc: "Great Denim Jeans.",
      img: "images/img-3.jpg",
    },
    {
      id: "thyfhcbcv",
      name: "T-Shirt",
      price: 300,
      desc: "T-Shirts with great Design.",
      img: "images/img-4.jpg",
    },
    {
      id: "thiecbawdjksadjk",
      name: "Half Sleeve Shirt",
      price: 500,
      desc: "Summer friendly Beach Shirts.",
      img: "images/img-5.jpg",
    },
    {
      id: "iuertrywebncdjksadjk",
      name: "Denim Shorts",
      price: 600,
      desc: "Feel free in these airy denim shorts.",
      img: "images/img-6.jpg",
    },
    {
      id: "thierytbvcbvzdhadjk",
      name: "Jacket",
      price: 3500,
      desc: "Astonishing Jackets for Winter.",
      img: "images/img-7.jpg",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      name: "Cargos",
      price: 700,
      desc: "Cargos for the One's.",
      img: "images/img-8.jpg",
    },
    {
      id: "cbvxbcvsceldk",
      name: "Kurta",
      price: 850,
      desc: "Let's go some Ethnic.",
      img: "images/img-9.jpg",
    },
    {
      id: "oiopijmjkhuihb",
      name: "Wrist Watch",
      price: 1200,
      desc: "Great deals on Wrist watches.",
      img: "images/img-10.jpg",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "Sunglasses",
      price: 400,
      desc: "Shields for you eyes but Classy.",
      img: "images/img-11.jpg",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Sneakers",
      price: 1800,
      desc: "Every Men's love - Sneakers.",
      img: "images/img-12.jpg",
    },
  ];